Fix implicit conversion error when compiling with MSVC
error C4244: 'function': conversion from 'int' to 'float', possible loss of data

`i` can't be float because it is also used as an array subscript