simd4f: Fix a compilation error
Not sure why the missing semicolon didn't get caught before.

Error:

In file included from graphene-simd4f.c:42:0:
graphene-simd4f.c: In function 'graphene_simd4f_reciprocal':
graphene-simd4f.h:863:3: error: expected ';' before '}' token
   }))
   ^
graphene-simd4f.c:439:10: note: in expansion of macro
'graphene_simd4f_reciprocal'
   return graphene_simd4f_reciprocal (s);
          ^
Makefile:817: recipe for target 'libgraphene_1_0_la-graphene-simd4f.lo' failed

Compiler:

$ aarch64-linux-android-gcc --version
aarch64-linux-android-gcc (GCC) 4.9.x 20150123 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Command:

make[3]: Entering directory '/home/arun/code/gstreamer/cerbero/build/sources/android_universal/arm64/graphene-1.4.0/src'
/bin/sh ../libtool  --tag=CC   --mode=compile ccache aarch64-linux-android-gcc -fuse-ld=gold -std=gnu99 -DHAVE_CONFIG_H -I.  -DGRAPHENE_COMPILATION=1 -DG_LOG_DOMAIN=\"Graphene\" -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_30 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -I../src -I../src -DGRAPHENE_ENABLE_DEBUG -DG_DISABLE_CAST_CHECKS --sysroot=/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64 -I/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64/usr/include -DANDROID -DPIC -O3 -ffast-math -fstrict-aliasing -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Wcast-align -Wno-unused-local-typedefs -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -fvisibility=hidden  -I/home/arun/code/gstreamer/cerbero/build/dist/android_universal/arm64/include/glib-2.0 -I/home/arun/code/gstreamer/cerbero/build/dist/android_universal/arm64/lib/glib-2.0/include      -Wall -g  --sysroot=/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64 -I/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64/usr/include -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -fPIC -DANDROID -DPIC -Wa,--noexecstack -MT libgraphene_1_0_la-graphene-simd4f.lo -MD -MP -MF .deps/libgraphene_1_0_la-graphene-simd4f.Tpo -c -o libgraphene_1_0_la-graphene-simd4f.lo `test -f 'graphene-simd4f.c' || echo './'`graphene-simd4f.c
libtool: compile:  ccache aarch64-linux-android-gcc -fuse-ld=gold -std=gnu99 -DHAVE_CONFIG_H -I. -DGRAPHENE_COMPILATION=1 -DG_LOG_DOMAIN=\"Graphene\" -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_30 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -I../src -I../src -DGRAPHENE_ENABLE_DEBUG -DG_DISABLE_CAST_CHECKS --sysroot=/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64 -I/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64/usr/include -DANDROID -DPIC -O3 -ffast-math -fstrict-aliasing -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Wcast-align -Wno-unused-local-typedefs -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -fvisibility=hidden -I/home/arun/code/gstreamer/cerbero/build/dist/android_universal/arm64/include/glib-2.0 -I/home/arun/code/gstreamer/cerbero/build/dist/android_universal/arm64/lib/glib-2.0/include -Wall -g --sysroot=/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64 -I/home/arun/code/gstreamer/cerbero/build/android-ndk-r12b/platforms/android-21/arch-arm64/usr/include -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -fPIC -DANDROID -DPIC -Wa,--noexecstack -MT libgraphene_1_0_la-graphene-simd4f.lo -MD -MP -MF .deps/libgraphene_1_0_la-graphene-simd4f.Tpo -c graphene-simd4f.c  -fPIC -DPIC -o .libs/libgraphene_1_0_la-graphene-simd4f.o
In file included from graphene-simd4f.c:42:0:
graphene-simd4f.c: In function 'graphene_simd4f_reciprocal':
graphene-simd4f.h:863:3: error: expected ';' before '}' token
   }))
   ^
graphene-simd4f.c:439:10: note: in expansion of macro 'graphene_simd4f_reciprocal'
   return graphene_simd4f_reciprocal (s);
          ^
Makefile:817: recipe for target 'libgraphene_1_0_la-graphene-simd4f.lo' failed